# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecurityFirst' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecurityFirst
  pod 'Alamofire'
  pod 'RxSwift' 
  pod 'KeychainSwift', '~> 11.0'
  pod 'SwiftyJSON'

  target 'SecurityFirstTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecurityFirstUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
